name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          pip install -r backend/order-service/requirements.txt
          pip install -r backend/payment-service/requirements.txt
          pip install -r backend/user-service/requirements.txt

      - name: Run backend tests
        run: |
          pytest backend/order-service
          pytest backend/payment-service
          pytest backend/user-service

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Test frontend
        working-directory: frontend
        run: npm test -- --ci

      - name: Install contract dependencies
        working-directory: smart-contracts
        run: npm install

      - name: Lint smart contracts
        working-directory: smart-contracts
        run: npm run lint

      - name: Test smart contracts
        working-directory: smart-contracts
        run: npm test
